Sprint 11
mp3moto/ImageFeed pull request #4
Opened 2022-12-19 17:18 UTC by mp3moto

По поводу задания на устранение гонок. Мое приложение по своей навигации само по себе исключает состояние гонки, поэтому я не стал перегружать его лишними проверками, которые никогда не сработают.

2022-12-19 21:07 UTC, ABashkirova requested changes
Запустила дебагер, ради интереса, вот так у тебя приложение потекло:
<img width="254" alt="Снимок экрана 2022-12-19 в 22 34 44" src="https://user-images.githubusercontent.com/20269264/208523995-c7dd9887-44bc-401d-8cda-00b6e268760c.png">

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/Auth/AuthViewController.swift
> +            case .failure(_):
Можно опускать параметры
```suggestion
            case .failure:
```

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/Auth/AuthViewController.swift
> +                    controller: self) { _ in
Слабо ссылку захватить нужно, ты же ее усилил разыменовав в guard выше

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/Auth/OAuth2TokenStorage.swift
> +            }
зачем-то использовал guard, который в итоге не понадобился, имею ввиду, что если после guard нет вообще кода – то ты делаешь что-то не так с ним

плюс очень много проверок для set-ера. Если уж так выходит, то лучше использовать функции

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/Auth/WebViewViewController.swift
> +        }*/
Для чего тут такой большой коммент? 🎅🏻?

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/Auth/WebViewViewController.swift
> +            switch(err.code) {
```suggestion
            switch err.code {
```

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/Auth/WebViewViewController.swift
> +            switch(err.code) {
для err.code можно написать экстеншен, который будет возвращать текстовое представление ошибки, чтобы здесь эту елочку не писать

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/Services/AlertService.swift
> +    func show(_ id: String? = nil) {
давай разделять смысловые блоки одной пустой строкой

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/Services/DataStorage.swift
> +     */
так, очень интересно, но давай удалим весь этот класс?

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/Services/ProfileImageService.swift
> +                url: PublicProfileURL!,
если тебе в username придет строка примерно такого вида {!!!!} – получишь за анврап падение в рантайме

давай писать безопасный код. 

Каждый анврап в тестовом проекте, проекте из портфолио - должен быть уместным, ты должен уметь объяснить почему это здесь можно было сделать. Джун, который бездумно будет форс анврапить на проекте – никому не нужен. 

Литература, как раз по твоему примеру
https://www.hackingwithswift.com/quick-start/understanding-swift/when-should-you-force-unwrap-optionals-in-swift


```suggestion
            let PublicProfileURL = URL(string: "https://api.unsplash.com/users/\(username)")
            let req: RequestFactoryProtocol = RequestFactory()

            guard let request = req.createRequest(
                url: PublicProfileURL!,
```

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/Services/ProfileService.swift
> +    private var _profile: Profile?
какие-то штучки из питона. Зачем так сложно?

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/Services/ProfileService.swift
> +    private var _profile: Profile?
вообще с нижним подчеркиванием пишут ребята с опытом в других языках :) чистые ios-еры такое не используют)

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/Services/RequestFactory.swift
> +            break
зачем break?

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/SplashViewController.swift
> +        profileService.fetchProfile(completion: { result in
а ссылку кто будет ослаблять?

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/SplashViewController.swift
> +                    if error as! ProfileServiceError == ProfileServiceError.emptyToken {
опять форс операция, а можно же писать безопасный код

if case ProfileServiceError.emptyToken = (error as? ProfileServiceError)

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/SplashViewController.swift
> +                        KeychainWrapper.standard.removeObject(forKey: "Auth token")
мне не очень нравится, что KeychainWrapper не инкапсулирован в DataStorage, который сделан как раз для токена

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/Unsplash/Structs.swift
> +        return output
Задачка со звездочкой – написать код без форс анврапов :)

2022-12-19 21:07 UTC, ABashkirova commented on Profile/ProfileViewController.swift
> +        profileImageServiceObserver = NotificationCenter.default.addObserver(
а зачем сохоранять ссылку на обсервер? как будет использован дальше?

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/SplashViewController.swift
> +        }
излишнее уводить на главную очередь

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/SplashViewController.swift
> +                        let alert = AlertService(
Очень большая простыня получается, здесь пора бить на функции

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/Auth/OAuth2TokenStorage.swift
> +            }
в ветке else можно было бы реализовать удаление токена из стораджа, чтобы не делать это руками в другом вью контроллере

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/SplashViewController.swift
> +    static let shared = SplashViewController()
А зачем статическая на vc?

2022-12-19 21:07 UTC, ABashkirova commented on ImageFeed/Services/ProfileService.swift
> +    private let profileImageService = ProfileImageService.shared
сервис есть, но не используется

2022-12-19 21:08 UTC, ABashkirova commented on ImageFeed/Services/ProfileImageService.swift
> +                url: PublicProfileURL!,
PublicProfileURL - в верхнем camelCase, тоже надо поправить, это константа, а не тип, нечего ей с большой буквы называться

2022-12-20 14:37 UTC, mp3moto commented on ImageFeed/Services/RequestFactory.swift
> +            break
Перепутал с PHP (

2022-12-20 16:54 UTC, mp3moto commented on ImageFeed/Services/ProfileService.swift
> +    private var _profile: Profile?
@ABashkirova поясните, пожалуйста. У меня сложная реализация set и get или подчеркивание выбивается из общего стиля? )

2022-12-20 19:25 UTC, ABashkirova commented on ImageFeed/Services/RequestFactory.swift
> +            break
о, буду знать что в PHP так :)

2022-12-22 07:38 UTC, closed without merging